name: Run Crypto Bot

on:
  push:
    branches: [main]
  schedule:
    - cron: "*/30 * * * *"  # setiap 30 menit

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot
      run: python run.py
