name: Run Bot Manual

on:
  workflow_dispatch:  # Memungkinkan eksekusi manual dari UI GitHub

jobs:
  run:
    name: Execute Python Bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; exit 1; fi

      - name: Verify environment variables
        run: |
          echo "Checking secrets..."
          if [ -z "${{ secrets.BYBIT_API_KEY }}" ]; then echo "❌ Missing BYBIT_API_KEY"; exit 1; fi
          if [ -z "${{ secrets.BYBIT_API_SECRET }}" ]; then echo "❌ Missing BYBIT_API_SECRET"; exit 1; fi
          if [ -z "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]; then echo "❌ Missing TELEGRAM_BOT_TOKEN"; exit 1; fi
          if [ -z "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then echo "❌ Missing TELEGRAM_CHAT_ID"; exit 1; fi
          echo "✅ All secrets are present."

      - name: Run Python bot script
        env:
          BYBIT_API_KEY: ${{ secrets.BYBIT_API_KEY }}
          BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Starting bot script..."
          python bybit_futures.py
